import 'package:flutter/material.dart';
import 'package:flutterapp/clinicaappapp/generatedhomewidget/generated/GeneratedServiceWidget.dart';
import 'package:flutterapp/clinicaappapp/generatedhomewidget/generated/GeneratedBannerWidget1.dart';
import 'package:flutterapp/clinicaappapp/generatedhomewidget/generated/GeneratedBannerWidget2.dart';
import 'package:flutterapp/clinicaappapp/generatedhomewidget/generated/GeneratedPackageWidget.dart';
import 'package:flutterapp/clinicaappapp/generatedhomewidget/generated/GeneratedTitleWidget.dart';
import 'package:flutterapp/clinicaappapp/generatedhomewidget/generated/GeneratedAvtWidget.dart';
import 'package:flutterapp/clinicaappapp/generatedhomewidget/generated/GeneratedSearchWidget.dart';
import 'package:flutterapp/clinicaappapp/generatedhomewidget/generated/GeneratedBannerWidget.dart';
import 'package:flutterapp/clinicaappapp/generatedhomewidget/generated/GeneratedHamMenuWidget.dart';

/* Frame Home
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHomeWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 251, 251, 251),
                ),
              ),
              Positioned(
                left: 24.0,
                top: 96.0,
                right: null,
                bottom: null,
                width: 181.0,
                height: 56.0,
                child: GeneratedTitleWidget(),
              ),
              Positioned(
                left: 315.0,
                top: 44.0,
                right: null,
                bottom: null,
                width: 36.0,
                height: 36.0,
                child: GeneratedAvtWidget(),
              ),
              Positioned(
                left: 24.0,
                top: 44.0,
                right: null,
                bottom: null,
                width: 36.0,
                height: 36.0,
                child: GeneratedHamMenuWidget(),
              ),
              Positioned(
                left: 60.0,
                top: 182.0,
                right: null,
                bottom: null,
                width: 255.0,
                height: 147.0,
                child: GeneratedBannerWidget(),
              ),
              Positioned(
                left: 40.0,
                top: 174.0,
                right: null,
                bottom: null,
                width: 295.0,
                height: 147.0,
                child: GeneratedBannerWidget1(),
              ),
              Positioned(
                left: 24.0,
                top: 132.0,
                right: null,
                bottom: null,
                width: 327.0,
                height: 181.0,
                child: GeneratedBannerWidget2(),
              ),
              Positioned(
                left: 24.0,
                top: 345.0,
                right: null,
                bottom: null,
                width: 327.0,
                height: 52.0,
                child: GeneratedSearchWidget(),
              ),
              Positioned(
                left: 24.0,
                top: 417.0,
                right: null,
                bottom: null,
                width: 328.0,
                height: 136.0,
                child: GeneratedServiceWidget(),
              ),
              Positioned(
                left: 24.0,
                top: 573.0,
                right: null,
                bottom: null,
                width: 327.0,
                height: 196.0,
                child: GeneratedPackageWidget(),
              )
            ]),
      ),
    ));
  }
}
