import 'package:flutter/material.dart';
import 'package:flutterapp/clinicaappapp/generatedonboardwidget/generated/GeneratedGroup1Widget.dart';
import 'package:flutterapp/clinicaappapp/generatedonboardwidget/generated/GeneratedHEATHYAPPWidget.dart';
import 'package:flutterapp/clinicaappapp/generatedonboardwidget/generated/GeneratedSkipWidget.dart';
import 'package:flutterapp/clinicaappapp/generatedonboardwidget/generated/GeneratedTextWidget.dart';
import 'package:flutterapp/clinicaappapp/generatedonboardwidget/generated/GeneratedButtonWidget.dart';
import 'package:flutterapp/clinicaappapp/generatedonboardwidget/generated/GeneratedIllustrationWidget.dart';

/* Frame Onboard
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedOnboardWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 251, 251, 251),
                ),
              ),
              Positioned(
                left: 24.0,
                top: 48.0,
                right: null,
                bottom: null,
                width: 131.0,
                height: 34.0,
                child: GeneratedHEATHYAPPWidget(),
              ),
              Positioned(
                left: 24.0,
                top: 469.0,
                right: null,
                bottom: null,
                width: 327.0,
                height: 120.0,
                child: GeneratedTextWidget(),
              ),
              Positioned(
                left: 163.5,
                top: 649.0,
                right: null,
                bottom: null,
                width: 48.0,
                height: 8.0,
                child: GeneratedGroup1Widget(),
              ),
              Positioned(
                left: 111.0,
                top: 700.0,
                right: null,
                bottom: null,
                width: 155.0,
                height: 52.0,
                child: GeneratedButtonWidget(),
              ),
              Positioned(
                left: 318.0,
                top: 52.0,
                right: null,
                bottom: null,
                width: 38.0,
                height: 29.0,
                child: GeneratedSkipWidget(),
              ),
              Positioned(
                left: 49.0,
                top: 162.0,
                right: null,
                bottom: null,
                width: 259.0,
                height: 268.0,
                child: GeneratedIllustrationWidget(),
              )
            ]),
      ),
    ));
  }
}
