import 'package:flutter/material.dart';
import 'package:flutterapp/clinicaappapp/generatedappointmentwidget/generated/GeneratedIllustrationWidget3.dart';
import 'package:flutterapp/clinicaappapp/generatedappointmentwidget/generated/GeneratedGroup18Widget.dart';
import 'package:flutterapp/clinicaappapp/generatedappointmentwidget/generated/GeneratedHamMenuWidget1.dart';
import 'package:flutterapp/clinicaappapp/generatedappointmentwidget/generated/GeneratedApointmentWidget.dart';
import 'package:flutterapp/clinicaappapp/generatedappointmentwidget/generated/GeneratedGroup17Widget.dart';
import 'package:flutterapp/clinicaappapp/generatedappointmentwidget/generated/GeneratedYourComplaintWidget.dart';
import 'package:flutterapp/clinicaappapp/generatedappointmentwidget/generated/GeneratedGroup15Widget.dart';
import 'package:flutterapp/clinicaappapp/generatedappointmentwidget/generated/GeneratedScheduleWidget.dart';
import 'package:flutterapp/clinicaappapp/generatedappointmentwidget/generated/GeneratedFrame16Widget.dart';
import 'package:flutterapp/clinicaappapp/generatedappointmentwidget/generated/GeneratedDateWidget.dart';
import 'package:flutterapp/clinicaappapp/generatedappointmentwidget/generated/GeneratedTextWidget2.dart';
import 'package:flutterapp/clinicaappapp/generatedappointmentwidget/generated/GeneratedOtherWidget.dart';
import 'package:flutterapp/clinicaappapp/generatedappointmentwidget/generated/GeneratedDrYumiNickersonWidget.dart';
import 'package:flutterapp/clinicaappapp/generatedappointmentwidget/generated/GeneratedFrame1Widget1.dart';
import 'package:flutterapp/clinicaappapp/generatedappointmentwidget/generated/GeneratedHamMenuWidget2.dart';

/* Frame Appointment
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAppointmentWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 315.0,
                top: 44.0,
                right: null,
                bottom: null,
                width: 36.0,
                height: 36.0,
                child: GeneratedHamMenuWidget1(),
              ),
              Positioned(
                left: 131.0,
                top: 48.0,
                right: null,
                bottom: null,
                width: 119.0,
                height: 33.0,
                child: GeneratedApointmentWidget(),
              ),
              Positioned(
                left: 24.0,
                top: 116.0,
                right: null,
                bottom: null,
                width: 327.0,
                height: 175.0,
                child: GeneratedFrame16Widget(),
              ),
              Positioned(
                left: 40.0,
                top: 132.0,
                right: null,
                bottom: null,
                width: 217.0,
                height: 34.0,
                child: GeneratedDrYumiNickersonWidget(),
              ),
              Positioned(
                left: 217.0,
                top: 94.0,
                right: null,
                bottom: null,
                width: 159.0,
                height: 197.0,
                child: GeneratedIllustrationWidget3(),
              ),
              Positioned(
                left: 24.0,
                top: 44.0,
                right: null,
                bottom: null,
                width: 36.0,
                height: 36.0,
                child: GeneratedHamMenuWidget2(),
              ),
              Positioned(
                left: 25.0,
                top: 351.0,
                right: null,
                bottom: null,
                width: 324.0,
                height: 56.0,
                child: GeneratedGroup15Widget(),
              ),
              Positioned(
                left: 313.0,
                top: 319.0,
                right: null,
                bottom: null,
                width: 43.0,
                height: 29.0,
                child: GeneratedOtherWidget(),
              ),
              Positioned(
                left: 24.0,
                top: 319.0,
                right: null,
                bottom: null,
                width: 42.0,
                height: 29.0,
                child: GeneratedDateWidget(),
              ),
              Positioned(
                left: 24.0,
                top: 423.0,
                right: null,
                bottom: null,
                width: 78.0,
                height: 29.0,
                child: GeneratedScheduleWidget(),
              ),
              Positioned(
                left: 25.0,
                top: 523.0,
                right: null,
                bottom: null,
                width: 121.0,
                height: 26.0,
                child: GeneratedYourComplaintWidget(),
              ),
              Positioned(
                left: 24.0,
                top: 455.0,
                right: null,
                bottom: null,
                width: 156.0,
                height: 52.0,
                child: GeneratedGroup17Widget(),
              ),
              Positioned(
                left: 196.0,
                top: 455.0,
                right: null,
                bottom: null,
                width: 156.0,
                height: 52.0,
                child: GeneratedGroup18Widget(),
              ),
              Positioned(
                left: 25.0,
                top: 700.0,
                right: null,
                bottom: null,
                width: 324.0,
                height: 52.0,
                child: GeneratedFrame1Widget1(),
              ),
              Positioned(
                left: 24.0,
                top: 555.0,
                right: null,
                bottom: null,
                width: 325.0,
                height: 117.0,
                child: GeneratedTextWidget2(),
              )
            ]),
      ),
    ));
  }
}
